### ISSUE TITLE
Convert Social Care Client lookup

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#100]

**Comment by Moohan** [comment]
[SPSS code](https://github.com/Public-Health-Scotland/source-linkage-files/blob/master/2021-22/A05%20Prepare%20Social%20Care%20Client%20lookup.sps)

**Comment by Moohan** [comment]
Similar to the SC demographics.

We take the data (quarterly) then aggregate it to get the latest/most complete data for each year.

**Comment by Jennit07** [comment]
Completed/merged into mainR #151
