### ISSUE TITLE
Rename IT extracts (R version) 

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#144]
Once we hear back from IT/BI on new IT extract names, update IT extract R function names in line. E.g. tasknumber_PIS_year or tasknumber_LTCs/Deaths. Issue #128 already does this for SPSS - PR pending upon confirmation.

**Comment by Moohan** [comment]
This can be done now, as IT have changed the file names. I think we already did it even?
