### ISSUE TITLE
Review R conversion project

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#161]
We are progressing with the R scripts and agree that this might be a good time to do a mini review of what we have so far. It would be good to look at all the different scripts that we have so far and identify any improvements. Things to look for: 

- Best practice 
- Where blocks of code are re-used and can be wrapped into a function 
- Are functions working? Do they make sense? Can they be renamed or modified? 
- Are processes clear? 
- Can code be cut down?
- On Main-R do all checks pass on the build function?
- Is documentation up to date?

**Comment by Moohan** [comment]
Superceeded by #215
