### ISSUE TITLE
Update CIJ marker SPSS type

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#205]
Some years now have a length 4 CIJ marker i.e. > 999. This means that in older files CIJ marker is a length 3 string and newer it's a length 4.

We could add a line to alter the type to string 4 or even 5 `Alter type cij_marker (A5)` but actually we would be much better storing it as a number. @Jennit07 can you think of any reason switching `cij_marker` from a string to a number could break our or anyone else's code? I guess if you did something like `cij_marker == "1"` but I'm not sure why anyone would do that... I think we only use the `cij_marker` in C01 and the DD matching code but don't think either of those would be impacted by the change in type?

**Comment by Jennit07** [comment]
PR complete #213
