### ISSUE TITLE
Review the DN extract

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#207]
I think we're extracting quite a few variables which we don't end up using for anything. These should be removed from the BOXI extract and from the code (the csv read in bit).

**Comment by shintoLamp** [comment]
Looking through the DN code, the only variable we extract that we don't use in the processing is `duration_contact`. I wouldn't say it's a big deal to leave this in as it's only one column

**Comment by Jennit07** [comment]
Closing as Bateman looked at this going by his comment above
