### ISSUE TITLE
Create an index for the function reference

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#211]
The [`{pkgdown}`](https://pkgdown.r-lib.org/index.html) site for the SLFs [https://public-health-scotland.github.io/source-linkage-files/reference/index.html](https://public-health-scotland.github.io/source-linkage-files/reference/index.html) site for the SLFs [https://public-health-scotland.github.io/source-linkage-files/reference/index.html) currently lists all of the functions in alphabetical order as that's the default.

pkgdown has some customisation options to sort the functions into sections e.g. [dplyr's reference page](https://dplyr.tidyverse.org/reference/index.html). There are instructions for creating the reference index here: [https://pkgdown.r-lib.org/reference/build_reference.html?q=index#reference-index]()

We should add an index for the function reference, particularly it would be good to use the `has_concept()` helper which links up with the roxygen `@family` tag.

**Comment by catherineholland1** [comment]
closed with #244
