### ISSUE TITLE
BUG with dates in tests

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#269]
Looks good for A&E tests. There is a small bug where the dates are not converting into numeric properly and causing the tests to show -100%. I will approve/merge this for now and create a separate issue as this will also affect other tests

_Originally posted by @Jennit07 in https://github.com/Public-Health-Scotland/source-linkage-files/pull/239#pullrequestreview-1007606837_

**Comment by Jennit07** [comment]
PR complete #279
