### ISSUE TITLE
R Conversion SOPs / help documentation

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#295]
We could do with a few extra bits of documentation. I'm happy to handle most of them, please add any other ideas to this list though.

- [ ] More detail on the review process - basically expand the [review process](https://github.com/Public-Health-Scotland/source-linkage-files/blob/main-R/R_development_SOP.md#review-process) section in the existing SOP.
- [ ] How to catch-up your local branch to the remote version - e.g. when you've opened a pull request and a GitHub action has made a commit.
- [ ] How to catch-up your local branch to main-R for to incorporate a recently merged change.
- [ ] How to catch-up your local branch to main-R for when there are merge-conflicts / dealing with merge conflicts generally.

**Comment by Jennit07** [comment]
PR completed #817  will close this issue now
