### ISSUE TITLE
Check scripts using `get_source_extract_path`

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#311]
Example: 
`readr::read_rds(get_source_extract_path(year, "Deaths", ext = "rds"))`

Creating this issue to remind us to go back and check scripts which use `get_source_extract_path`. We just need to remove the `ext = "rds"` as this is not needed. The function uses `get_file_paths` which specifies the file as rds by default. This might only affect tests scripts as I think extract scripts may have been changed.

**Comment by shintoLamp** [comment]
Checked the scripts, none of the scripts which use `get_source_extract_path` use the `ext` parameter any more. Closing the issue.
