### ISSUE TITLE
Fix documentation in `produce_source_nrs_tests`

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#326]
There is a build warning that was caused by #306, where a parameter in the new test function wasn't properly documented. This is now causing the build check to fail on every PR which is trying to merge to `main-R` e.g. [The workflow notes for #278 ](https://github.com/Public-Health-Scotland/source-linkage-files/runs/7727970846?check_suite_focus=true#:~:text=%E2%9D%AF%20checking%20Rd%20%5Cusage,%E2%80%98max_min_vars%E2%80%99)

**Comment by shintoLamp** [comment]
Merged fix for this issue in #327
