### ISSUE TITLE
C04 - Add on NSU cohort

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#335]
C04 - Add on NSU cohort conversion

This script is not very long and we imagine this to be a top level script which calls upon functions. This is because we don't always have a NSU extract for latest years.

For example, something like this: 
- if year is <= latest year then run some code. else skip over this.

We discussed that we would prioritise including this in the process

**Comment by shintoLamp** [comment]
#381 now merged, closing issue
