### ISSUE TITLE
C06 - Deaths fixes 

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#338]
C06 - Deaths fixes 

In this file we match on the CHI-Deaths data and attempt to work out the last valid activity. We decide what date to use and if the last is the NRS date then we use that one. 

We can potentially convert this later and should check how analysts use this one.

A potential quick fix for skipping through this: 
- take the NRS data and apply this to the death dates then ignore the CHI deaths data for now

**Comment by SwiftySalmon** [comment]
dealt with. We now use NRS boxi extract
