### ISSUE TITLE
Update `get_it_prescribing_path` to find the latest file by default

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#354]
Currently the function `get_it_prescribing_path()` has a required parameter `it_reference` which by default uses `it_extract_ref()`.

It would be good to not need to specify an `it_reference` at all so the function just uses the latest file by default, with an option to specify a specific `it_reference` if desired. I think we could then remove `it_extract_ref()` as it would not be needed, and would mean one fewer thing we need to change and check every quarter.

We could probably use the existing `find_latest_file()` for this.

**Comment by shintoLamp** [comment]
See #368 for ongoing work
