### ISSUE TITLE
New function to clear out old files

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#355]
A simple function which could be run before or after an update to clear out any files which are not needed.

I'm not sure what the parameters would look like...

It should probably find files to delete and then give a nice message to check before deleting. Probably in sections i.e.

```R
clear_files_function(some_params)

#> Cleaning SLF_extracts
#> Would you like to delete the old IT extracts:
#> <List of IT extracts to be deleted>
#> [y/n]
#> ...
#> 
#> Cleaning the 1920 folder
#> Would you like to delete the old extracts:
#> <List of 1920 csv/gz extracts to be deleted>
#> [y/n]
#> ...
#> Would you like to delete the old processed files:
#> <list ...>
#> [y/n]
#> 
#> End.
#> Deleted x/y found files in hscdiip saving XX GB
#> Deleted x/y found files in sourcedev saving XX GB
```

See [askYesNo()](https://rdrr.io/r/utils/askYesNo.html).

**Comment by shintoLamp** [comment]
Looks like this issue has been addressed in #460 so will close
