### ISSUE TITLE
Create a function for computing changed sc_id.

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#360]
We should create a function for computing changed sc_id.

_Originally posted by @Moohan in https://github.com/Public-Health-Scotland/source-linkage-files/pull/324#discussion_r947979959_

Take some social care data, with `sending_lca`, `social_care_id`, `period` and `chi` variables.

For each `chi` and `sending_lca` if there are multiple `sc_id`s, then replace them with the latests submitted one.

**Comment by Jennit07** [comment]
Completed in #440
