### ISSUE TITLE
Update the sc_sending_loc to LCA function

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#371]
We missed at least 1 LCA (North Lan), see the below change / code which just needs copying to `main-r`

Looks good to me, all the LCAs are there now 😆

We do need to remember to copy these changes to the main-r branch.

_Originally posted by @Moohan in https://github.com/Public-Health-Scotland/source-linkage-files/pull/370#pullrequestreview-1083869719_

**Comment by Jennit07** [comment]
Copied this to main R branch PR #372 open
