### ISSUE TITLE
Review lookup tests 

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#406]
The function `write_tests_xlsx` now includes a year parameter which does not fit how the lookup tests are set up. These need reviewed

**Comment by lizihao-anu** [comment]
As for the issue "write_tests_xlsx now looks for a year parameter ", would it be ok to allow year to be a missing argument? We can use if else to separate the cases with or without year? Hope I make myself clear.

For write_tests_xlsx.R, argument year = NULL, and line 39 can be changed to

  if(missing(year)){
    sheet_name_dated <- glue::glue("{sheet_name}_{date_today}")
  }else{
    sheet_name_dated <- glue::glue("{year}_{sheet_name}_{date_today}")
  }

**Comment by Moohan** [comment]
@lizihao-anu solution sounds like a good one to me, let's do it!
