### ISSUE TITLE
Investigate non-matching SPSS vs R test outputs

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#477]
Please check and update the spreadsheet on teams with the findings. Check instances where the SPSS and R versions do not match cost tests: 

- [x] Outpatients
- [x] CMH 
- [x] Care Home

**Comment by lizihao-anu** [comment]
- Outpatients
The issue was costs from SPSS and R do not match. It is because SPSS outputs do not add each month costs to cost_net_total properly while R outputs do.

- CMH
In year 1718, more than 700 records in R outputs have missing postcodes, leading to less episode numbers in health boards.

**Comment by lizihao-anu** [comment]
See excel spreedesheet for more details
