### ISSUE TITLE
Review function names

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#490]
I have had this on my list for a while but haven't got round to it or added an issue as this will be a big change. Im adding this and will assign to myself to remember to review this in the new year. Currently we have the name structure set up `process_extract_xxx` or `process_tests_xxx` which indicate scripts which have been converted into a function. However this looks a bit confusing when we consider other functions which deal with tests and create test flags for comparison. This is in the format `produce_xxx_tests` which i think looks too similar to other functions which are not really related. I mentioned before that a proposed rename could be to have this in the format `build_tests_xxx` which will differentiate this. If anyone has any other rename suggestions for these functions (or others) please comment on this Issue.

**Comment by SwiftySalmon** [comment]
do we reckon this needs done?? I think most function names are fine... unless there's anything specific that you can think of?
