### ISSUE TITLE
Make sure that all test workbook sheet names are snake_case

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#508]
Make sure that all test workbook sheet names i.e `sheet_name` in `write_tests_xlsx()` are snake_case. i.e. lowercase with underscores.

It will make it much easier if we ever want to read them back in if the names are styled consistently.

_Originally posted by @Moohan in https://github.com/Public-Health-Scotland/source-linkage-files/pull/503#discussion_r1049388330_

**Comment by Moohan** [comment]
We could add a check + error to `write_tests_xlsx()` to check the casing e.g.
```r
if (grepl("^([a-z]+_?)+[a-z]+$", sheetname)) {
  cli::cli_abort("Error message about lower case / snake case")
}
```

This could highlight any existing issues and would stop any future ones being introduced.

**Comment by Jennit07** [comment]
To do - relates to the test workbooks rather than scripts being in snake case
