### ISSUE TITLE
Reduce the number of dependencies 

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#580]
R-CMD-CHECK give a build note commenting on the large number of dependencies we have. It would be sensible to review this and reduce them where possible. We should take a systematic approach and where we are depending on a package but only using it in limited places we should try to re-write the code to not require it.

An obvious example would be to replace `glue::glue(...)` with `stringr::str_glue(...)` Since we use `{stringr}` for many other functions.

**Comment by SwiftySalmon** [comment]
Things that might have alternatives

**Uses future or future.callrpackage**
- [ ]  _targets.R - future::plan(future.callr::callr)  this is the only place these two packages are used. 

**Uses hms package**
- [ ]  process_extract_cmh.R - keytime2
- [ ] process_extract_gp_ooh - keytime1 and keytime2

**Uses R markdown package**
- [ ]  process_costs_rmd.R - not sure if we use this

**Uses scales package**
- [ ]  costs_care_home.Rmd I don't think we use any of these scripts?
- [ ] costs_district_nursing.Rmd
- [ ] costs_gp_ooh.Rmd
- [ ] costs_home_care.Rmd
- [ ] hc_methodology

**Uses stringdist package**
- [ ]  fill_ch_names.R used for jaccard and cosine matching

**Uses tarchetypes package**
- [ ]  _targets.R 

**Uses zoo package**
- [ ]  process_extract_consultations.R   - zoo::na.locf  I think this is the same as fill but possibly specialised for dates?
