### ISSUE TITLE
Add Source of Referral from CMH to `refsource`

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#59]
Currently `refsource` contains values from A&E, Outpatients and GP OoH. CMH also has a referral source variable that isn't currently included. The CMH variable is missing for some boards but mostly complete for others.

- [ ] Check the codes currently in use for A&E, Outpatients and GP OoH.
- [ ] Check the codes for CMH.
- [ ] See if any other datasets have a referral source variable which we might want to include e.g. SMR? DN? Social Care etc.
- [ ] Harmonize the codes if possible, probably using A&E / Outpatients (or SMR) as the base and modify others to match.

**Comment by Moohan** [comment]
Possibly not worth doing if CMH is to be stopped. TBC if we'll leave historic CMH data in the SLFs or not...

**Comment by SwiftySalmon** [comment]
@Jennit07  @lizihao-anu  thoughts on closing this issue?

**Comment by lizihao-anu** [comment]
Yeah, I agree to close this issue.
