### ISSUE TITLE
Fix issue with `create_monthly_costs`

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#634]
This function fails when the data doesn't include an episode in every month, for example, see `process_extract_care_home` for 1718.

@lizihao-anu made changes recently and it's this bit which is causing the issue. I think that Zihao originally had code that was working and I suggested a change that has now turned out to have broken it!

Assigning it to Zihao initially but anyone could pick it up asap.

**Comment by Jennit07** [comment]
Changes from #600

**Comment by lizihao-anu** [comment]
Pull #665 should have closed this issue but it seems not although the merge has been completed. Manually close this issue now.
