### ISSUE TITLE
Fix bugs in the episode file

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#645]
The latest version of the episode file has some issues which need investigating and possibly fixing.

- [ ] Care Home - Changes to numbers; might be difficult as the code is long/complicated and has been rewritten from SPSS to R. Also the data will have changed a little bit so it will never match 100%
- [ ] District Nursing - Some issues with costs, likely due to the HB codes used 2016 vs 2018 vs 2019.
- [ ] GPOoHs - Some strange issues with costs.

**Comment by shintoLamp** [comment]
I believe these issues have now been resolved in the episode file
