### ISSUE TITLE
Review check year valid function

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#649]
I dont think this is working correctly for Social Care 

```
  } else if (year <= "1617") {
    if (type %in% c("CH", "HC", "SDS", "AT")) {
      return(FALSE)
    }
```

when i try check_year_valid("1415", "HC") this returns TRUE when this should be FALSE

**Comment by Jennit07** [comment]
PR open #654

**Comment by shintoLamp** [comment]
PR #654 merged now, so will assume this behaviour is corrected
