### ISSUE TITLE
Rename `convert_sending_location_to_lca` for clarity

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#688]
This could be renamed to make it clear that sending location is from Social Care e.g. `convert_sc_sending_location_to_lca <- function(sc_sending_location)`

_Originally posted by @Moohan in https://github.com/Public-Health-Scotland/source-linkage-files/pull/638#discussion_r1220007876_

**Comment by SwiftySalmon** [comment]
Jen sorted thi issue September 2023
