### ISSUE TITLE
Rewrite `case_when` statements using `case_match()` where appropriate

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#692]
This function should be re-written using `case_match()` e.g.

```r
lca <- dplyr::case_match(
    ca_var,
    c("S12000033", "Aberdeen City") ~ "01",
    ... ,
   )
```

_Originally posted by @Moohan in https://github.com/Public-Health-Scotland/source-linkage-files/pull/638#discussion_r1226660216_

**Comment by Jennit07** [comment]
PR completed #780 will close this issue now
