### ISSUE TITLE
Use the features of `parquet` where possible

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#694]
I think there's scope for us to use `col_select` and even `as_data_frame = FALSE` in more places, now we're using `parquet` as standard.

`as_data_frame` works by returning an 'Arrow Table' instead of a tibble which you then use `{dplyr}` functions on and finally a `dplyr::collect()`, at which point it actually reads the (needed) data from the file and runs the commands thus making it more efficient. It's equivalent to using `{dbplyr}` on a database but for `parquet` files.

_Originally posted by @Moohan in https://github.com/Public-Health-Scotland/source-linkage-files/pull/693#discussion_r1235191211_

**Comment by lizihao-anu** [comment]
I have checked the codes and we have used `parquet` features where possible. So I am going to close this issue.
