### ISSUE TITLE
Individual file issues identified from Tests

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#701]
Testing the 1718 file has identified a few issues with the individual file: 

```[tasklist]
### Indiv file issues
- [x] HB drop to 0 - I have identified an issue with the variable `hbrescode` which does not have codes and only a `1` in each row
- [x] Maternity episodes/beddays - a large drop
- [x] Maternity inpatient and daycase episodes - a large drop
- [x] Maternity inpatient and daycase costs - a large drop
- [x] `health_net_costs` variable showing as 0 on all rows
- [x] Large increase in a&e attendance
- [ ] https://github.com/Public-Health-Scotland/source-linkage-files/issues/757
- [x] variable `total_cost_net_inc_dnas` still available in the file should now be `health_net_costs`?
- [x] `total_dd_non_code9beddays` - all rows are 0
- [x] `total_dd_code9beddays` - all rows are 0
```

```[tasklist]
### Test code issues
- [ ] drop in preventable beddays - I think this needs to be added to the test code
- [x] `hc_total_cost` - missing from tests
- [x] `hc_personal_hours_cost` - missing from tests
- [x] `hc_non_personal_hours_cost` - missing from tests
- [x] `hc_reablement_hours_cost` - missing from tests
```

**Comment by lizihao-anu** [comment]
I have fixed the bug of the preventable_beddyas, preventable_admissions, and ae_attendances. I suspect the issues with maternity and home care are coming from the episode file. For more details see the file `Jun_2023_1718_tests_20230621.xlsx` in `hsciip` folder.

**Comment by Jennit07** [comment]
> I have fixed the bug of the preventable_beddyas, preventable_admissions, and ae_attendances. I suspect the issues with maternity and home care are coming from the episode file. For more details see the file `Jun_2023_1718_tests_20230621.xlsx` in `hsciip` folder.

Thanks @lizihao-anu I have ran the tests on your updated file `source-individual-file-1718_zihao.parquet` please see the tests called `Jun_2023_1718_tests_zihao_20230623` for the results
