### ISSUE TITLE
Sort out the Postcode lookup / matching - variables with issues include `hbrescode` (HB2018), `datazone` and `hscp`

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#738]

**Comment by Jennit07** [comment]
I've sorted `hscp` on this branch and i think `hbrescode` was done in #724 for the individual file. For datazone, i think this is an extra variable because it is taken from BOXI. We take `datazone2011` from the postcode lookup so i think we can drop `datazone` from this altogether. 

In the `fill_geographies` function we list `datazone` within the `check_variables_exist` but we don't actually use this anywhere in the script from what i can see. @Moohan Can you think of any reasons why we would need `datazone` before i remove this? Thanks

**Comment by Moohan** [comment]
> In the `fill_geographies` function we list `datazone` within the `check_variables_exist` but we don't actually use this anywhere in the script from what i can see. @Moohan Can you think of any reasons why we would need `datazone` before i remove this?

I think we used to take `datazone` i.e. the datazone from the data mart which is attached to the episode, and if the postcode couldn't match a new datazone through the lookup (either postcode is invalid or missing), we'd use the original one. - The only situation this actually helps is when the postcode is missing/invalid but datazone isn't though, and I guess that's a very niche situation...

As long as we have the `datazone2011` correctly named and no odd `datazone` variable left over that should be fine!

**Comment by Jennit07** [comment]
As discussed on a call, i have renamed `datazone` in the datamart and made use of this in the `fill_geographies` function. PR open #744
