### ISSUE TITLE
Archive DN and CMH data

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#777]
Move the DN and CMH data to an archive location (possibly a new folder on sourcedev or hscdiip), could change the permissions of the file to 440 (read-only)? 

Then update the `get_file_path_*` functions if required.

**Comment by Moohan** [comment]
* Option 1 - write protect files
 * Option 2 - archive folder with symlink (`ln -s`)
 * Option 3 - archive folder elsewhere.
 * Option 4 - archive folder + update code to point to new location.
 * Option 5 - Note file to highlight don't delete.

Options not mutually exclusive.

**Comment by Jennit07** [comment]
PR completed #785  will close this issue now
