### ISSUE TITLE
Fix/investigate build warning

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/source-linkage-files#790]
Assigning this to @lizihao-anu as he wrote the data.table individual file code.

There's a persistent build warning e.g.
https://github.com/Public-Health-Scotland/source-linkage-files/actions/runs/5799684816/job/15720207031#step:6:78 
```
Note: possible error in '`:=`(ch_no_cost = max(ch_no_cost), ': unused arguments (ch_no_cost = max(ch_no_cost), ch_ep_start = min(record_keydate1), ch_ep_end = max(ch_ep_end), ch_cost_per_day = mean(ch_cost_per_day)) at aggregate_by_chi.R:206 
```

It's [this line in `aggregate_ch_episodes()`](https://github.com/Public-Health-Scotland/source-linkage-files/blob/bb3dbd5d0e056249c94252dab19636a9ef44e494/R/aggregate_by_chi.R#L206) - it works but the check doesn't like it, so I wonder if it could be tweaked or written differently?

**Comment by Jennit07** [comment]
PR completed #797  will close this issue now
