### ISSUE TITLE
More than once social care id to chi

### ISSUE THREAD

**Issue by SwiftySalmon** [Public-Health-Scotland/source-linkage-files#851]
Found an issue where multiple `social_care_id` match to a chi but all are flagged as the latest `social_care_id` . This creates duplicates in output. Spoke to Mark in Social Care and they suspected that this could be an issue as `latest_flag` is becoming less reliable over time but this is the first case that's been found. 

Currently fixing missing end dates and the issues that this causes and decided this needs its own investigation and solution. Also social care hasn't decided how they are going to deal with this yet so maybe wait and see what they come up with?

**Comment by SwiftySalmon** [comment]
sds uses this function ` replace_sc_id_with_latest()` to deal with this. There's nothing in place for AT though. Unsure about other SC areas

**Comment by Jennit07** [comment]
Split out into a new branch

**Comment by SwiftySalmon** [comment]
Fixed this for match 2023 update for sds and demographics. If this works will be rolled out
