### ISSUE TITLE
Deaths investigation - Create activity after death flag

### ISSUE THREAD

**Issue by SwiftySalmon** [Public-Health-Scotland/source-linkage-files#862]
Add a flag to episode and individual files that will flag if activity is after the death date. 

There is sometimes activity recorded after death and this is due to various data quality or admin issues. The idea here is to add a flag so that analysts can decide for themselves if they want to remove these cases

**Comment by Jennit07** [comment]
Confirmed at the SLF information session that this would be useful for analysts to have. I've changed the tag on this to high priority and removed the on hold label

**Comment by rchlv** [comment]
Please refer to the "Investigation into activity after death" report for detailed information about the issues found and methodology proposed for creating the activity after death flag.
