### ISSUE TITLE
Review copy to hscdiip script

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#888]
Process for copying over final episode and individual files from sourcedev to hscdiip – script first deletes exiting file then writes to hscdiip but gets stuck early on before writing file. Alternative is to use PUTTY, but need to install on laptop

**Comment by lizihao-anu** [comment]
```
> for (i in 1:length(folders)) {
+   timer <- Sys.time()
+   print(stringr::str_glue("{folders[i]} starts at {Sys.time()}"))
+   folder_path <- file.p .... [TRUNCATED] 
1920 starts at 2024-02-27 10:10:15
[1] "source-episode-file-1920.parquet"    "source-individual-file-1920.parquet"
file size is 931.924534797668.
[1] 7.223492
2021 starts at 2024-02-27 10:17:29
[1] "source-episode-file-2021.parquet"    "source-individual-file-2021.parquet"
file size is 839.647627830505.
[1] 6.240084
```
The `move_to_hscdiip` script works fine. I guess that it looks stuck because it takes approximately 7 minutes to finish writing files for data in one year.

**Comment by lizihao-anu** [comment]
Use putty instead now for faster file moving
