### ISSUE TITLE
Bug - `keytime1` and `keytime2` are in the wrong format

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#909]
In the episode files, `keytime1` and `keytime2` are in seconds instead of hrs:mins:secs. I have had a look into this and i have ran the episode file manually but i cannot get to the route cause of this issue. 

When i run this manually, everything looks as expected and in the format H:M:S. However when you read in the file from sourcedev this shows seconds. The seconds can be easily converted into H:M:S but in our documentation we state this should be in date time format (H:M:S).

Not sure if this is a read in/write to disk issue as the code looks fine to me and i cannot replicate the issue or find the route cause. Opening an issue to keep this on our list to fix for the update.

**Comment by SwiftySalmon** [comment]
Seems to be completely random as to whether it reads it in as seconds or hms. Can't replicate issue or see what is causing it. Suggest we update documentation with how to change time to hms instead. It's easy enough to do and less hassle than whatever this is.
