### ISSUE TITLE
Review quarter calculation functions

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#915]
Linked to #897 

The following functions need reviewed when the care home methodology is reviewed. These functions are only used in `process_sc_all_care_homes` which may not be needed due to variables extracted from the platform such as `period_end_date` which achieve the same logic and less code. 

- `start_fy_quarter`
- `end_fy_quarter`
- `start_next_fy_quarter`
- `end_next_fy_quarter`

**Comment by SwiftySalmon** [comment]
process_sc_all_carehomes has been dealt with and script rewritten. Notes are on sharepoint
