### ISSUE TITLE
Investigate extra variable in individual file

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#944]
Extra variable called `...1` between `hl1_in_fy` and `arth_date` has appeared in the individual file. Investigate why this has pulled through and correct this. Check episode file to ensure this is also not there.

**Comment by Jennit07** [comment]
`...84` appearing in the episode file as well

**Comment by lizihao-anu** [comment]
Both problems in ep_file and individual_files are caused by raw data of ltc in hscdiip IT_extracts folder. The raw data has an unexpected column located in the first. This column is row number for each row.
