### ISSUE TITLE
CUP marker for A&E attendances & admissions together

### ISSUE THREAD

**Issue by Jennit07** [Public-Health-Scotland/source-linkage-files#974]
A suggestion from the drop in was whether it would be possible to create a marker for social care data and attendances to A&E. The social care team already have code for doing this and a LIST analyst will share their code with us. Investigate whether we can create a new variable to accommodate.

**Comment by lizihao-anu** [comment]
This work can be done by the cup_marker and cup_pathway, which is added in #775 and #776 that is included in the current September 2024 update. There is no need to add any extra variables, which keeps SLF reamaining tidy and clean. In terms of the request of selecting any cups that include "EA", meaning an emergency resulting in acute. There could be anything before "EA" or after "EA", say like "EEEAO" or "EANOS". This can be easily achieved from the customers' end by adding a filter `dplyr::filter(grepl("EA", cup_pathway))`.
