### ISSUE TITLE
Death dates

### ISSUE THREAD

**Issue by SwiftySalmon** [Public-Health-Scotland/source-linkage-files#986]
R/process_it_chi_deaths.R 

For this we should be using chi_death_date and then joining with BOXI extract

Default should be death date from boxi nrs death date, and filling in affected death dates from chi_death_date from IT extract

Or if CHIs are affected by CHI seeding issue then use chi_death_date from IT extract (needs investigation on how to identify cases)

**Comment by lizihao-anu** [comment]
Close by #987
